In [3]:
import pandas as pd

tabela = pd.read_csv("exportacao_full.csv")
display(tabela)

FileNotFoundError: [Errno 2] No such file or directory: 'exportacao_full.csv'

In [2]:
tabela = tabela.loc[tabela['Year']>=2016, :]
tabela = tabela.loc[tabela['Country']=="France", :]
display(tabela)

,Year,Month,Country,City,SH4 Code,SH4 Description,SH2 Code,SH2 Description,Economic Block,US$ FOB,Net Weight
494040,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",Europe,79360,14150
494041,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),79360,14150
494042,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",Europe,69412,9385
494043,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),69412,9385
494044,2016,1,France,Alfenas - MG,901,"Coffee, whether or not roasted or decaffeinate...",9,"Coffee, tea, maté and spices",Europe,180914,57600
...,...,...,...,...,...,...,...,...,...,...,...
12980015,2020,12,France,Vinhedo - SP,8424,Mechanical appliances (whether or not hand-ope...,84,"Nuclear reactors, boilers, machinery and mecha...",European Union (EU),2316,4
12980016,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,Europe,27060,26400
12980017,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,European Union (EU),27060,26400
12980018,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,Europe,31111,23045
12980019,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,European Union (EU),31111,23045

In [4]:
tabela.to_csv("exportacoes_franca.csv", index=False)

In [6]:
tabela = pd.read_csv("exportacoes_franca.csv")
display(tabela)

,Year,Month,Country,City,SH4 Code,SH4 Description,SH2 Code,SH2 Description,Economic Block,US$ FOB,Net Weight
0,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",Europe,79360,14150
1,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),79360,14150
2,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",Europe,69412,9385
3,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),69412,9385
4,2016,1,France,Alfenas - MG,901,"Coffee, whether or not roasted or decaffeinate...",9,"Coffee, tea, maté and spices",Europe,180914,57600
...,...,...,...,...,...,...,...,...,...,...,...
142355,2020,12,France,Vinhedo - SP,8424,Mechanical appliances (whether or not hand-ope...,84,"Nuclear reactors, boilers, machinery and mecha...",European Union (EU),2316,4
142356,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,Europe,27060,26400
142357,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,European Union (EU),27060,26400
142358,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,Europe,31111,23045
142359,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,European Union (EU),31111,23045

### Informações Gerais
Quantas Linhas tem a tabela existe algum valor vazio que deveria ser tratado?

In [ ]:
#Função : .info()

display(tabela.info())

<class 'pandas.DataFrame'>
RangeIndex: 142360 entries, 0 to 142359
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Year             142360 non-null  int64
 1   Month            142360 non-null  int64
 2   Country          142360 non-null  str
 3   City             142360 non-null  str
 4   SH4 Code         142360 non-null  int64
 5   SH4 Description  142360 non-null  str
 6   SH2 Code         142360 non-null  int64
 7   SH2 Description  142360 non-null  str
 8   Economic Block   142360 non-null  str
 9   US$ FOB          142360 non-null  int64
 10  Net Weight       142360 non-null  int64
dtypes: int64(6), str(5)
memory usage: 11.9 MB

None

### Como foi as ultimas importações para a frança ao longo dos anos?
crie uma tabela com os anos 2016, 2017, 2018, 2019 e 2020 e o valor em US$ de Exportações

In [19]:
#Função groupby = agrupar no caso todas as linhas do anos de 2016 em diante

tabela_anos_exportacao = tabela[["Year","US$ FOB"]].groupby("Year").sum()

display(tabela_anos_exportacao)

         US$ FOB
Year
2016  4615500082
2017  4448705456
2018  5239424416
2019  5218723612
2020  3967594810

In [ ]:
# Quero formatar os valores na tabela colocando $ ponto virgula:
# Crio uma function formatar

def formatar (valor):
    valor_formatado= f"US$ {valor:,}"
    return valor_formatado

tabela_anos_exportacao["US$ FOB"] = tabela_anos_exportacao["US$ FOB"].apply(formatar)                            #.apply aplica a função

display(tabela_anos_exportacao)

                US$ FOB
Year
2016  US$ 4,615,500,082
2017  US$ 4,448,705,456
2018  US$ 5,239,424,416
2019  US$ 5,218,723,612
2020  US$ 3,967,594,810

### Quais os produtos mais exportados ao longo de todo o período?
queremos saber os produtos com maior valor US$ de exportação

In [24]:
tabela_produtos_exportados= tabela[["SH2 Description","US$ FOB"]].groupby("SH2 Description").sum()

#deixar o valores em ordem decrescentes usando o .sort_values()

tabela_produtos_exportados = tabela_produtos_exportados.sort_values(by="US$ FOB", ascending= False)

tabela_produtos_exportados["US$ FOB"] = tabela_produtos_exportados["US$ FOB"].apply(formatar)


display(tabela_produtos_exportados)

                                                              US$ FOB
SH2 Description
Residues and waste from the food industries; ot...  US$ 5,641,498,484
Ores, slag and ash                                  US$ 3,404,353,274
Nuclear reactors, boilers, machinery and mechan...  US$ 1,889,781,694
Pulp of wood or of other fibrous cellulosic mat...  US$ 1,855,424,642
Aircraft, spacecraft, and parts thereof             US$ 1,253,007,710
...                                                               ...
Umbrellas, sun umbrellas, walking-sticks, seat-...         US$ 18,872
Cork and articles of cork                                  US$ 10,974
Wool, fine or coarse animal hair; horsehair yar...          US$ 2,540
Tin and articles thereof                                    US$ 2,460
Photographic or cinematographic goods                         US$ 148

[97 rows x 1 columns]

### Em 2020 qual a cidade mais exportou pra frança?
Em valores US$

In [29]:
tabela_2020 = tabela.loc[tabela["Year"] == 2020, :]
tabela_cidades_2020= tabela_2020[["City","US$ FOB"]].groupby("City").sum()
tabela_cidades_2020 = tabela_cidades_2020.sort_values(by="US$ FOB", ascending=False)
tabela_cidades_2020["US$ FOB"]= tabela_cidades_2020["US$ FOB"].apply(formatar)
display(tabela_cidades_2020)

                                     US$ FOB
City
Duque de Caxias - RJ         US$ 279,405,596
Luís Eduardo Magalhães - BA  US$ 265,328,132
Ponta Grossa - PR            US$ 187,777,016
São José dos Campos - SP     US$ 172,939,276
Rio de Janeiro - RJ          US$ 122,522,214
...                                      ...
Não-Me-Toque - RS                     US$ 42
Cubatão - SP                          US$ 40
Holambra - SP                         US$ 10
São Sebastião do Caí - RS              US$ 6
Quatro Pontes - PR                     US$ 0

[648 rows x 1 columns]

### Quais os produtos mais exportados (em US$) que as 2 maiores cidades (em exportação)

In [42]:
cidade = tabela_cidades_2020.index[0]
print(f"A cidade que mais exportou produtos para a frança foi{cidade}")

tabela_cidade= tabela_2020.loc[tabela_2020["City"] == cidade, :]
tabela_produtos_cidade= tabela_cidade[["SH2 Description","US$ FOB"]].groupby("SH2 Description").sum()
tabela_produtos_cidade = tabela_produtos_cidade.sort_values(by="US$ FOB", ascending= False)
tabela_produtos_cidade["US$ FOB"]= tabela_produtos_cidade["US$ FOB"].apply(formatar)
display(tabela_produtos_cidade)

A cidade que mais exportou produtos para a frança foiDuque de Caxias - RJ

                                                            US$ FOB
SH2 Description
Nuclear reactors, boilers, machinery and mechan...  US$ 185,816,982
Mineral fuels, mineral oils, bituminous substan...   US$ 67,355,688
Articles of iron or steel                             US$ 9,118,714
Residues and waste from the food industries; ot...    US$ 4,014,274
Optical, photographic, cinematographic instrume...    US$ 3,013,092
Nickel and articles thereof                           US$ 2,951,286
Electrical machinery and equipment and parts th...    US$ 2,595,048
Lead and articles thereof                             US$ 1,660,180
Rubber and articles thereof                           US$ 1,379,296
Organic chemicals                                       US$ 535,136
Vehicles other than railway or tramway rolling-...      US$ 353,958
Plastics and articles thereof                           US$ 228,638
Aluminium and articles thereof                          US$ 168,522
Copper and articles thereof                             US$ 138,466
Tools, implements, cutlery, spoons and forks, o...       US$ 33,864
Articles of stone, plaster, cement, asbestos, m...       US$ 16,856
Miscellaneous chemical products                          US$ 11,984
Glass and glassware                                       US$ 8,430
Railway or tramway locomotives, rolling-stock a...        US$ 3,666
Paper and paperboard; articles of paper pulp, o...        US$ 1,516